# Generated by Django 5.1.1 on 2024-09-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lista',
        ),
    ]
